<?xml version="1.0" encoding="utf-8"?>
<!--
This file catalogues IDL syntax elements contained in
the IDL HTML documentation set.
Catalog created on Wed Jul 08 01:57:40 2015
-->
<!DOCTYPE CATALOG [
   <!ELEMENT CATALOG (CLASS*, ROUTINE*, SYSVAR*, STATEMENT*)*>
   <!ATTLIST CATALOG name CDATA #IMPLIED>
   <!ATTLIST CATALOG version CDATA #IMPLIED>
   <!ELEMENT ROUTINE (SYNTAX | ARGUMENT | KEYWORD)*>
   <!ATTLIST ROUTINE name CDATA #IMPLIED>
   <!ATTLIST ROUTINE link CDATA #IMPLIED>
   <!ATTLIST ROUTINE alias_to CDATA #IMPLIED>
   <!ATTLIST ROUTINE classname CDATA #IMPLIED>
   <!ELEMENT STATEMENT EMPTY >
   <!ATTLIST STATEMENT name CDATA #IMPLIED>
   <!ATTLIST STATEMENT link CDATA #IMPLIED>
   <!ATTLIST STATEMENT alias_to CDATA #IMPLIED>
   <!ELEMENT SYNTAX EMPTY>
   <!ATTLIST SYNTAX name CDATA #IMPLIED>
   <!ATTLIST SYNTAX type CDATA #IMPLIED>
   <!ELEMENT ARGUMENT EMPTY>
   <!ATTLIST ARGUMENT name CDATA #IMPLIED>
   <!ATTLIST ARGUMENT link CDATA #IMPLIED>
   <!ELEMENT KEYWORD EMPTY>
   <!ATTLIST KEYWORD name CDATA #IMPLIED>
   <!ATTLIST KEYWORD link CDATA #IMPLIED>
   <!ELEMENT CLASS (SUPERCLASS*, PROPERTY*, METHOD*)>
   <!ATTLIST CLASS name CDATA #IMPLIED>
   <!ATTLIST CLASS link CDATA #IMPLIED>
   <!ATTLIST CLASS special CDATA #IMPLIED>
   <!ELEMENT SUPERCLASS EMPTY>
   <!ATTLIST SUPERCLASS name CDATA #IMPLIED>
   <!ATTLIST SUPERCLASS link CDATA #IMPLIED>
   <!ELEMENT PROPERTY EMPTY>
   <!ATTLIST PROPERTY name CDATA #IMPLIED>
   <!ATTLIST PROPERTY link CDATA #IMPLIED>
   <!ATTLIST PROPERTY get CDATA #IMPLIED>
   <!ATTLIST PROPERTY set CDATA #IMPLIED>
   <!ATTLIST PROPERTY init CDATA #IMPLIED>
   <!ATTLIST PROPERTY registered CDATA #IMPLIED>
   <!ELEMENT METHOD (SYNTAX | ARGUMENT | KEYWORD)*>
   <!ATTLIST METHOD class CDATA #IMPLIED>
   <!ATTLIST METHOD name CDATA #IMPLIED>
   <!ATTLIST METHOD link CDATA #IMPLIED>
   <!ELEMENT ODOT_TAG EMPTY>
   <!ATTLIST ODOT_TAG name CDATA #IMPLIED>
   <!ELEMENT SYSVAR (FIELD*)>
   <!ATTLIST SYSVAR name CDATA #IMPLIED>
   <!ATTLIST SYSVAR link CDATA #IMPLIED>
   <!ATTLIST SYSVAR alias_to CDATA #IMPLIED>
   <!ELEMENT FIELD EMPTY>
   <!ATTLIST FIELD name CDATA #IMPLIED>
   <!ATTLIST FIELD link CDATA #IMPLIED>
]>
<CATALOG name="IDL">
  <ROUTINE name="WRITE_NRIF" link="WRITE_NRIF.htm" alias_to="" classname="">
    <DESCRIPTION name="Write NCAR Raster Interchange Format rasterfiles" />
    <SYNTAX name="WRITE_NRIF, File, Image [, R, G, B]" type="pro" />
    <ARGUMENT name="File" link="WRITE_NRIF.htm" />
    <ARGUMENT name="Image" link="WRITE_NRIF.htm" />
    <ARGUMENT name="R, G, B" link="WRITE_NRIF.htm" />
  </ROUTINE>
  <ROUTINE name="MAP_GRID" link="MAP_GRID_Procedure.htm" alias_to="" classname="">
    <DESCRIPTION name="Draw parallels and meridians over a Direct Graphics map" />
    <SYNTAX name="MAP_GRID [, /BOX_AXES | [, CLIP_TEXT=0] [, LATALIGN=value{0.0 to 1.0}] [, LONALIGN=value{0.0 to 1.0}] [, LATLAB=longitude] [, LONLAB=latitude] [, ORIENTATION=clockwise_degrees_from_horiz]] [, CHARSIZE=value] [, COLOR=index] [, /FILL_HORIZON] [, GLINESTYLE={0 | 1 | 2 | 3 | 4 | 5}] [, GLINETHICK=value] [, /HORIZON] [, INCREMENT=value] [, LABEL=n{label_every_nth_gridline}] [, LATDEL=degrees] [, LATNAMES=array, LATS=vector] [, LONDEL=degrees] [, LONNAMES=array, LONS=vector] [, MAP_STRUCTURE=structure] [, /NO_GRID]" type="pro" />
    <SYNTAX name="Graphics Keywords: [, /T3D] [, ZVALUE=value{0 to 1}]" type="pro" />
    <KEYWORD name="BOX_AXES" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884049" />
    <KEYWORD name="CHARSIZE" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884053" />
    <KEYWORD name="CLIP_TEXT" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884060" />
    <KEYWORD name="COLOR" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884063" />
    <KEYWORD name="FILL_HORIZON" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884066" />
    <KEYWORD name="GLINESTYLE" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884069" />
    <KEYWORD name="GLINETHICK" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884075" />
    <KEYWORD name="HORIZON" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884078" />
    <KEYWORD name="INCREMENT" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884081" />
    <KEYWORD name="LABEL" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884084" />
    <KEYWORD name="LATALIGN" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884087" />
    <KEYWORD name="LATDEL" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884090" />
    <KEYWORD name="LATLAB" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884093" />
    <KEYWORD name="LATNAMES" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884096" />
    <KEYWORD name="LATS" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884101" />
    <KEYWORD name="LONALIGN" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884106" />
    <KEYWORD name="LONDEL" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884109" />
    <KEYWORD name="LONLAB" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884112" />
    <KEYWORD name="LONNAMES" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884115" />
    <KEYWORD name="LONS" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884120" />
    <KEYWORD name="MAP_STRUCTURE" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884125" />
    <KEYWORD name="NO_GRID" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884131" />
    <KEYWORD name="ORIENTATION" link="MAP_GRID_Procedure.htm#dg_routines_3604229493_884134" />
  </ROUTINE>
  <CLASS name="IDLffXMLDOMProcessingInstruction" link="IDLffXMLDOMProcessingIns.htm" special="">
    <SUPERCLASS name="IDLffXMLDOMNode" link="IDLffXMLDOMNode.htm#objects_ff_3755668711_1105014" />
    <METHOD class="IDLffXMLDOMProcessingInstruction" name="IDLffXMLDOMProcessingInstruction::Cleanup" link="IDLffXMLDOMProcessingIns2.htm">
      <SYNTAX name="Obj-&gt;Cleanup" type="pro" />
      <SYNTAX name="OBJ_DESTROY, Obj" type="pro" />
    </METHOD>
    <METHOD class="IDLffXMLDOMProcessingInstruction" name="IDLffXMLDOMProcessingInstruction::GetData" link="IDLffXMLDOMProcessingIns3.htm">
      <SYNTAX name="Result = Obj-&gt;[IDLffXMLDOMProcessingInstruction::]GetData()" type="func" />
    </METHOD>
    <METHOD class="IDLffXMLDOMProcessingInstruction" name="IDLffXMLDOMProcessingInstruction::GetTarget" link="IDLffXMLDOMProcessingIns4.htm">
      <SYNTAX name="Result = Obj-&gt;[IDLffXMLDOMProcessingInstruction::]GetTarget()" type="func" />
    </METHOD>
    <METHOD class="IDLffXMLDOMProcessingInstruction" name="IDLffXMLDOMProcessingInstruction::Init" link="IDLffXMLDOMProcessingIns5.htm">
    </METHOD>
    <METHOD class="IDLffXMLDOMProcessingInstruction" name="IDLffXMLDOMProcessingInstruction::SetData" link="IDLffXMLDOMProcessingIns6.htm">
      <SYNTAX name="Obj-&gt;[IDLffXMLDOMProcessingInstruction::]SetData, Content" type="pro" />
      <ARGUMENT name="Content" link="IDLffXMLDOMProcessingIns6.htm" />
    </METHOD>
  </CLASS>
  <ROUTINE name="PUSHD" link="PUSHD.htm" alias_to="" classname="">
    <DESCRIPTION name="Push a directory to top of directory stack maintained by PUSHD/POPD" />
    <SYNTAX name="PUSHD, Dir" type="pro" />
    <ARGUMENT name="Dir" link="PUSHD.htm" />
  </ROUTINE>
  <ROUTINE name="H5S_GET_SELECT_HYPER_BLOCKLIST" link="H5S_GET_SELECT_HYPER_BLO.htm" alias_to="" classname="">
    <SYNTAX name="Result = H5S_GET_SELECT_HYPER_BLOCKLIST(Dataspace_id [, START=value] [, NUMBER=value] )" type="func" />
    <ARGUMENT name="Dataspace_id" link="H5S_GET_SELECT_HYPER_BLO.htm" />
    <KEYWORD name="START" link="H5S_GET_SELECT_HYPER_BLO.htm#HDF5_209170119_1009382" />
    <KEYWORD name="NUMBER" link="H5S_GET_SELECT_HYPER_BLO.htm#HDF5_209170119_1009385" />
  </ROUTINE>
  <ROUTINE name="FZ_ROOTS" link="FZ_ROOTS.htm" alias_to="" classname="">
    <DESCRIPTION name="Find the roots of a complex polynomial using Laguerre’s method" />
    <SYNTAX name="Result = FZ_ROOTS(C [, /DOUBLE] [, EPS=value] [, /NO_POLISH] )" type="func" />
    <ARGUMENT name="C" link="FZ_ROOTS.htm" />
    <KEYWORD name="DOUBLE" link="FZ_ROOTS.htm#F_848155245_52525" />
    <KEYWORD name="EPS" link="FZ_ROOTS.htm#F_848155245_902541" />
    <KEYWORD name="NO_POLISH" link="FZ_ROOTS.htm#F_848155245_902543" />
  </ROUTINE>
  <ROUTINE name="HDF_SD_ADDDATA" link="HDF_SD_ADDDATA.htm" alias_to="" classname="">
    <SYNTAX name="HDF_SD_ADDDATA, SDdataset_id, Data [, COUNT=vector] [, /NOREVERSE] [, START=vector] [, STRIDE=vector]" type="pro" />
    <ARGUMENT name="SDdataset_id" link="HDF_SD_ADDDATA.htm" />
    <ARGUMENT name="Data" link="HDF_SD_ADDDATA.htm" />
    <KEYWORD name="COUNT" link="HDF_SD_ADDDATA.htm#HDF_1733484267_1010486" />
    <KEYWORD name="NOREVERSE" link="HDF_SD_ADDDATA.htm#HDF_1733484267_1010489" />
    <KEYWORD name="START" link="HDF_SD_ADDDATA.htm#HDF_1733484267_1010492" />
    <KEYWORD name="STRIDE" link="HDF_SD_ADDDATA.htm#HDF_1733484267_1010495" />
  </ROUTINE>
  <ROUTINE name="BROYDEN" link="BROYDEN.htm" alias_to="" classname="">
    <DESCRIPTION name="Solve nonlinear equations using Broyden’s method" />
    <SYNTAX name="Result = BROYDEN( X, Vecfunc [, CHECK=variable] [, /DOUBLE] [, EPS=value] [, ITMAX=value] [, STEPMAX=value] [, TOLF=value] [, TOLMIN=value] [, TOLX=value] )" type="func" />
    <ARGUMENT name="X" link="BROYDEN.htm" />
    <ARGUMENT name="Vecfunc" link="BROYDEN.htm" />
    <KEYWORD name="CHECK" link="BROYDEN.htm#B_856805997_50283" />
    <KEYWORD name="DOUBLE" link="BROYDEN.htm#B_856805997_50286" />
    <KEYWORD name="EPS" link="BROYDEN.htm#B_856805997_50289" />
    <KEYWORD name="ITMAX" link="BROYDEN.htm#B_856805997_989330" />
    <KEYWORD name="STEPMAX" link="BROYDEN.htm#B_856805997_50292" />
    <KEYWORD name="TOLF" link="BROYDEN.htm#B_856805997_50295" />
    <KEYWORD name="TOLMIN" link="BROYDEN.htm#B_856805997_50298" />
    <KEYWORD name="TOLX" link="BROYDEN.htm#B_856805997_50301" />
  </ROUTINE>
  <ROUTINE name="CDF_LEAPSECONDS_INFO" link="CDF_LEAPSECONDS_INFO.htm" alias_to="" classname="">
    <SYNTAX name="Result = CDF_LEAPSECONDS_INFO( )" type="func" />
  </ROUTINE>
  <ROUTINE name="QROMO" link="QROMO.htm" alias_to="" classname="">
    <DESCRIPTION name="Evaluate an integral over an open interval" />
    <SYNTAX name="Result = QROMO(Func, A [, B] [, /DOUBLE] [, EPS=value] [, JMAX=value] [, K=value] [, /MIDEXP | , /MIDINF | , /MIDPNT | , /MIDSQL | , /MIDSQU] )" type="func" />
    <ARGUMENT name="Func" link="QROMO.htm" />
    <ARGUMENT name="A" link="QROMO.htm" />
    <ARGUMENT name="B" link="QROMO.htm" />
    <KEYWORD name="DOUBLE" link="QROMO.htm#Q_815714925_51594" />
    <KEYWORD name="EPS" link="QROMO.htm#Q_815714925_51597" />
    <KEYWORD name="JMAX" link="QROMO.htm#Q_815714925_51600" />
    <KEYWORD name="K" link="QROMO.htm#Q_815714925_51603" />
    <KEYWORD name="MIDEXP" link="QROMO.htm#Q_815714925_51606" />
    <KEYWORD name="MIDINF" link="QROMO.htm#Q_815714925_51609" />
    <KEYWORD name="MIDPNT" link="QROMO.htm#Q_815714925_51612" />
    <KEYWORD name="MIDSQL" link="QROMO.htm#Q_815714925_51615" />
    <KEYWORD name="MIDSQU" link="QROMO.htm#Q_815714925_51618" />
  </ROUTINE>
  <ROUTINE name="H5G_CLOSE" link="H5G_CLOSE.htm" alias_to="" classname="">
    <SYNTAX name="H5G_CLOSE, Group_id" type="pro" />
    <ARGUMENT name="Group_id" link="H5G_CLOSE.htm" />
  </ROUTINE>
  <ROUTINE name="EOS_SW_COMPINFO" link="EOS_SW_COMPINFO.htm" alias_to="" classname="">
    <SYNTAX name="Result = EOS_SW_COMPINFO(swathID, fieldname, compcode, compparm)" type="func" />
    <ARGUMENT name="swathID" link="EOS_SW_COMPINFO.htm" />
    <ARGUMENT name="fieldname" link="EOS_SW_COMPINFO.htm" />
    <ARGUMENT name="compcode" link="EOS_SW_COMPINFO.htm" />
    <ARGUMENT name="compparm" link="EOS_SW_COMPINFO.htm" />
  </ROUTINE>
  <ROUTINE name="POLYGON" link="POLYGON.htm" alias_to="" classname="">
    <DESCRIPTION name="Adds a polygon annotation to an existing graphic" />
    <SYNTAX name="graphic = POLYGON(X, Y, [, Z] [, Format]  [, Keywords=value][Properties=value])" type="func" />
    <ARGUMENT name="X" link="POLYGON.htm" />
    <ARGUMENT name="Y" link="POLYGON.htm" />
    <ARGUMENT name="Z" link="POLYGON.htm" />
    <ARGUMENT name="Format" link="POLYGON.htm" />
    <KEYWORD name="CONNECTIVITY" link="POLYGON.htm#CONNECTI" />
    <KEYWORD name="DATA" link="POLYGON.htm#DATA" />
    <KEYWORD name="DEVICE" link="POLYGON.htm#DEVICE" />
    <KEYWORD name="NORMAL" link="POLYGON.htm#NORMAL" />
    <KEYWORD name="RELATIVE" link="POLYGON.htm#RELATIVE" />
    <KEYWORD name="ANTIALIAS" link="POLYGON.htm#ANTIALIA" />
    <KEYWORD name="CLIP" link="POLYGON.htm#CLIP" />
    <KEYWORD name="COLOR" link="POLYGON.htm#COLOR" />
    <KEYWORD name="FILL_BACKGROUND" link="POLYGON.htm#FILL_BAC" />
    <KEYWORD name="FILL_COLOR" link="POLYGON.htm#FILL_COL" />
    <KEYWORD name="FILL_TRANSPARENCY" link="POLYGON.htm#FILL_TRA" />
    <KEYWORD name="HIDE" link="POLYGON.htm#HIDE" />
    <KEYWORD name="LINESTYLE" link="POLYGON.htm#LINESTYL" />
    <KEYWORD name="NAME" link="POLYGON.htm#NAME" />
    <KEYWORD name="PATTERN_BITMAP" link="POLYGON.htm#PBITMAP" />
    <KEYWORD name="PATTERN_ORIENTATION" link="POLYGON.htm#PORIENT" />
    <KEYWORD name="PATTERN_SPACING" link="POLYGON.htm#PSPACING" />
    <KEYWORD name="PATTERN_THICK" link="POLYGON.htm#PTHICK" />
    <KEYWORD name="POSITION" link="POLYGON.htm#POSITION" />
    <KEYWORD name="RGB_TABLE" link="POLYGON.htm#RGB_TABLE" />
    <KEYWORD name="THICK" link="POLYGON.htm#THICK" />
    <KEYWORD name="TRANSPARENCY" link="POLYGON.htm#TRANSPAR" />
    <KEYWORD name="UVALUE" link="POLYGON.htm#UVALUE" />
    <KEYWORD name="VERT_COLORS" link="POLYGON.htm#VERT_COLORS" />
    <KEYWORD name="WINDOW (Get Only)" link="POLYGON.htm#WINDOW" />
  </ROUTINE>
  <CLASS name="POLYGON" link="POLYGON.htm" special="yes">
    <PROPERTY name="ANTIALIAS" link="POLYGON.htm#ANTIALIA" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="CLIP" link="POLYGON.htm#CLIP" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="COLOR" link="POLYGON.htm#COLOR" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="FILL_BACKGROUND" link="POLYGON.htm#FILL_BAC" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="FILL_COLOR" link="POLYGON.htm#FILL_COL" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="FILL_TRANSPARENCY" link="POLYGON.htm#FILL_TRA" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="HIDE" link="POLYGON.htm#HIDE" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="LINESTYLE" link="POLYGON.htm#LINESTYL" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="NAME" link="POLYGON.htm#NAME" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="PATTERN_BITMAP" link="POLYGON.htm#PBITMAP" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="PATTERN_ORIENTATION" link="POLYGON.htm#PORIENT" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="PATTERN_SPACING" link="POLYGON.htm#PSPACING" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="PATTERN_THICK" link="POLYGON.htm#PTHICK" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="POSITION" link="POLYGON.htm#POSITION" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="RGB_TABLE" link="POLYGON.htm#RGB_TABLE" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="THICK" link="POLYGON.htm#THICK" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="TRANSPARENCY" link="POLYGON.htm#TRANSPAR" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="UVALUE" link="POLYGON.htm#UVALUE" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="VERT_COLORS" link="POLYGON.htm#VERT_COLORS" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="WINDOW (Get Only)" link="POLYGON.htm#WINDOW" get="Yes" set="Yes" init="Yes" registered="No" />
    <METHOD class="POLYGON" name="POLYGON::Close" link="../../IDL Graphics/Close Method.htm">
      <SYNTAX name="polygon.Close" type="pro" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::ConvertCoord" link="../../IDL Graphics/ConvertCoord Method.htm">
      <SYNTAX name="" type="pro" />
      <ARGUMENT name="X" link="ConvertCoord Method.htm" />
      <ARGUMENT name="Y" link="ConvertCoord Method.htm" />
      <ARGUMENT name="Z" link="ConvertCoord Method.htm" />
      <KEYWORD name="DATA" link="ConvertCoord Method.htm#lass=" />
      <KEYWORD name="DEVICE" link="ConvertCoord Method.htm#iTools_api_3860698369_1000127" />
      <KEYWORD name="NORMAL" link="ConvertCoord Method.htm#iTools_api_3860698369_1000130" />
      <KEYWORD name="RELATIVE" link="ConvertCoord Method.htm#lass=" />
      <KEYWORD name="TO_DATA" link="ConvertCoord Method.htm#iTools_api_3860698369_1000133" />
      <KEYWORD name="TO_DEVICE" link="ConvertCoord Method.htm#iTools_api_3860698369_1000139" />
      <KEYWORD name="TO_NORMAL" link="ConvertCoord Method.htm#iTools_api_3860698369_1000142" />
      <KEYWORD name="TO_RELATIVE" link="ConvertCoord Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::CopyWindow" link="../../IDL Graphics/CopyWindow Method.htm">
      <SYNTAX name="Result = polygon.CopyWindow( /ANTIALIAS, BORDER=integer, HEIGHT=integer, RESOLUTION=integer, TRANSPARENT=array, WIDTH=integer )" type="func" />
      <KEYWORD name="ANTIALIAS" link="CopyWindow Method.htm#lass=" />
      <KEYWORD name="BORDER" link="CopyWindow Method.htm#lass=" />
      <KEYWORD name="HEIGHT" link="CopyWindow Method.htm#lass=" />
      <KEYWORD name="RESOLUTION" link="CopyWindow Method.htm#lass=" />
      <KEYWORD name="TRANSPARENT" link="CopyWindow Method.htm#lass=" />
      <KEYWORD name="WIDTH" link="CopyWindow Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Delete" link="../../IDL Graphics/Delete Method.htm">
      <SYNTAX name="polygon.Delete" type="pro" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::GenerateCode" link="../../IDL Graphics/GenerateCode Method.htm">
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::GetData" link="../../IDL Graphics/GetData Method.htm">
      <SYNTAX name="polygon.GetData, Argument1, Argument2, ... Argumentn  [, BOTTOM_VALUES=value] [, CONNECTIVITY=value]" type="pro" />
      <KEYWORD name="BOTTOM_VALUES" link="GetData Method.htm#BOTTOM_V" />
      <KEYWORD name="CONNECTIVITY" link="GetData Method.htm#CONNECTI" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::GetValueAtLocation" link="../../IDL Graphics/GetValueAtLocation Method.htm">
      <SYNTAX name="Result = polygon.GetValueAtLocation( X, Y, Z  [, /DEVICE] [, /INTERPOLATE] [, /NORMAL] )" type="func" />
      <KEYWORD name="DEVICE" link="GetValueAtLocation Method.htm#lass=" />
      <KEYWORD name="INTERPOLATE" link="GetValueAtLocation Method.htm#lass=" />
      <KEYWORD name="NORMAL" link="GetValueAtLocation Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::MapForward" link="../../IDL Graphics/MapForward Method.htm">
      <SYNTAX name="Result = polygon.MapForward(Longitude [, Latitude] [, CONNECTIVITY=vector] [, /FILL] [, POLYGONS=variable] [, POLYLINES=variable] [,  /RADIANS] )" type="func" />
      <ARGUMENT name="Longitude" link="MapForward Method.htm" />
      <ARGUMENT name="Latitude" link="MapForward Method.htm" />
      <KEYWORD name="CONNECTIVITY" link="MapForward Method.htm#lass=" />
      <KEYWORD name="FILL" link="MapForward Method.htm#lass=" />
      <KEYWORD name="POLYGONS" link="MapForward Method.htm#lass=" />
      <KEYWORD name="POLYLINES" link="MapForward Method.htm#lass=" />
      <KEYWORD name="RADIANS" link="MapForward Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::MapInverse" link="../../IDL Graphics/MapInverse Method.htm">
      <SYNTAX name="Result = polygon.MapInverse(X [, Y] [, /RADIANS])" type="func" />
      <ARGUMENT name="X" link="MapInverse Method.htm" />
      <ARGUMENT name="Y" link="MapInverse Method.htm" />
      <KEYWORD name="RADIANS" link="MapInverse Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Order" link="../../IDL Graphics/Order Method.htm">
      <SYNTAX name="polygon.Order  [, /BRING_FORWARD]  [, /BRING_TO_FRONT]  [, /SEND_BACKWARD] [, /SEND_TO_BACK]" type="pro" />
      <KEYWORD name="BRING_FORWARD" link="Order Method.htm#lass=" />
      <KEYWORD name="BRING_TO_FRONT" link="Order Method.htm#lass=" />
      <KEYWORD name="SEND_BACKWARD" link="Order Method.htm#lass=" />
      <KEYWORD name="SEND_TO_BACK" link="Order Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Print" link="../../IDL Graphics/Print Method.htm">
      <SYNTAX name="polygon.Print [, /CENTIMETERS] [, HEIGHT=value] [, /LANDSCAPE] [, WIDTH=value] [, XMARGIN=value] [, YMARGIN=value]" type="pro" />
      <KEYWORD name="CENTIMETERS" link="Print Method.htm#lass=" />
      <KEYWORD name="HEIGHT" link="Print Method.htm#lass=" />
      <KEYWORD name="LANDSCAPE" link="Print Method.htm#lass=" />
      <KEYWORD name="WIDTH" link="Print Method.htm#lass=" />
      <KEYWORD name="XMARGIN" link="Print Method.htm#lass=" />
      <KEYWORD name="YMARGIN" link="Print Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Refresh" link="../../IDL Graphics/Refresh Method.htm">
      <SYNTAX name="polygon.Refresh [, /DISABLE]" type="pro" />
      <KEYWORD name="DISABLE" link="Refresh Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Rotate" link="../../IDL Graphics/Rotate Method.htm">
      <SYNTAX name="polygon.Rotate, Angle [, /DEFAULT] [, /RESET] [, /XAXIS] [, /YAXIS] [, /ZAXIS]" type="pro" />
      <ARGUMENT name="Angle" link="Rotate Method.htm" />
      <KEYWORD name="DEFAULT" link="Rotate Method.htm#lass=" />
      <KEYWORD name="RESET" link="Rotate Method.htm#lass=" />
      <KEYWORD name="XAXIS" link="Rotate Method.htm#iTools_api_3860698369_1007121" />
      <KEYWORD name="YAXIS" link="Rotate Method.htm#iTools_api_3860698369_1007124" />
      <KEYWORD name="ZAXIS" link="Rotate Method.htm#iTools_api_3860698369_1007127" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Save" link="../../IDL Graphics/Save Method.htm">
      <SYNTAX name="polygon.Save, Filename, /ANTIALIAS, /APPEND, BIT_DEPTH={0|1|2}, /BITMAP, BORDER=integer, /CENTIMETERS, /CLOSE, /CMYK, COMPRESSION={0|1|2}, HEIGHT=integer, LANDSCAPE, /MEMORY, PAGE_SIZE=value, RESOLUTION=integer, /REVERSIBLE, TRANSPARENT=array, WIDTH=integer, XMARGIN=integer, YMARGIN=integer" type="pro" />
      <ARGUMENT name="Filename" link="Save Method.htm" />
      <KEYWORD name="ANTIALIAS" link="Save Method.htm#lass=" />
      <KEYWORD name="APPEND" link="Save Method.htm#APPEND" />
      <KEYWORD name="BIT_DEPTH" link="Save Method.htm#lass=" />
      <KEYWORD name="BITMAP" link="Save Method.htm#lass=" />
      <KEYWORD name="BORDER" link="Save Method.htm#lass=" />
      <KEYWORD name="CENTIMETERS" link="Save Method.htm#lass=" />
      <KEYWORD name="CLOSE" link="Save Method.htm#lass=" />
      <KEYWORD name="CMYK" link="Save Method.htm#lass=" />
      <KEYWORD name="COMPRESSION" link="Save Method.htm#lass=" />
      <KEYWORD name="HEIGHT" link="Save Method.htm#lass=" />
      <KEYWORD name="LANDSCAPE" link="Save Method.htm#lass=" />
      <KEYWORD name="MEMORY" link="Save Method.htm#lass=" />
      <KEYWORD name="PAGE_SIZE" link="Save Method.htm#lass=" />
      <KEYWORD name="RESOLUTION" link="Save Method.htm#lass=" />
      <KEYWORD name="REVERSIBLE" link="Save Method.htm#lass=" />
      <KEYWORD name="TRANSPARENT" link="Save Method.htm#lass=" />
      <KEYWORD name="WIDTH" link="Save Method.htm#lass=" />
      <KEYWORD name="XMARGIN" link="Save Method.htm#lass=" />
      <KEYWORD name="YMARGIN" link="Save Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Scale" link="../../IDL Graphics/Scale Method.htm">
      <SYNTAX name="polygon.Scale, X, Y, Z [, /RESET]" type="pro" />
      <ARGUMENT name="X, Y, Z" link="Scale Method.htm" />
      <KEYWORD name="RESET" link="Scale Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Select" link="../../IDL Graphics/Select Method.htm">
      <SYNTAX name="polygon.Select [, /ADD] [, /ALL] [, /CLEAR] [, /TOGGLE] [, /UNSELECT]" type="pro" />
      <KEYWORD name="ADD" link="Select Method.htm#lass=" />
      <KEYWORD name="ALL" link="Select Method.htm#lass=" />
      <KEYWORD name="CLEAR" link="Select Method.htm#lass=" />
      <KEYWORD name="TOGGLE" link="Select Method.htm#lass=" />
      <KEYWORD name="UNSELECT" link="Select Method.htm#lass=" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::SetData" link="../../IDL Graphics/SetData Method.htm">
      <SYNTAX name="polygon.SetData, Argument1, Argument2, ... Argumentn [, CONNECTIVITY=value]" type="pro" />
      <KEYWORD name="CONNECTIVITY" link="SetData Method.htm#CONNECTI" />
    </METHOD>
    <METHOD class="POLYGON" name="POLYGON::Translate" link="../../IDL Graphics/Translate Method.htm">
      <SYNTAX name="polygon.Translate, X, Y, Z [, /DATA] [, /DEVICE] [, /NORMAL] [, /RESET]" type="pro" />
      <ARGUMENT name="X, Y, Z" link="Translate Method.htm" />
      <KEYWORD name="DATA" link="Translate Method.htm#lass=" />
      <KEYWORD name="DEVICE" link="Translate Method.htm#lass=" />
      <KEYWORD name="NORMAL" link="Translate Method.htm#lass=" />
      <KEYWORD name="RESET" link="Translate Method.htm#lass=" />
    </METHOD>
  </CLASS>
  <ROUTINE name="GRIB_SET_VALUES" link="GRIB_SET_VALUES.htm" alias_to="" classname="">
    <SYNTAX name="GRIB_SET_VALUES, Ghandle, Values" type="pro" />
    <ARGUMENT name="Ghandle" link="GRIB_SET_VALUES.htm" />
    <ARGUMENT name="Values" link="GRIB_SET_VALUES.htm" />
  </ROUTINE>
  <ROUTINE name="SEM_LOCK" link="SEM_LOCK.htm" alias_to="" classname="">
    <DESCRIPTION name="Attempt to gain the lock on an existing semaphore" />
    <SYNTAX name="Result = SEM_LOCK(strName)" type="func" />
    <ARGUMENT name="strName" link="SEM_LOCK.htm" />
  </ROUTINE>
  <ROUTINE name="IDL_Number" link="IDL_Number.htm" alias_to="" classname="">
    <KEYWORD name="TPOOL_MAX_ELTS" link="tpoolkeyw.html#tpoolkeyw_2501860834_95491" />
    <KEYWORD name="TPOOL_MIN_ELTS" link="tpoolkeyw.html#tpoolkeyw_2501860834_59989" />
    <KEYWORD name="TPOOL_NOTHREAD" link="tpoolkeyw.html#tpoolkeyw_2501860834_69180" />
  </ROUTINE>
  <CLASS name="IDL_Number" link="IDL_Number.htm" special="yes">
    <SUPERCLASS name="IDL_Variable" link="IDL_Variable.htm" />
    <METHOD class="IDL_Number" name="IDL_Number::Ceil" link="kanchor5926">
      <DESCRIPTION name="Compute the ceiling" />
      <SYNTAX name="Result = var.Ceil(  )" type="func" />
      <KEYWORD name="L64" link="IDL_Number.htm#lass=" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Floor" link="kanchor5927">
      <DESCRIPTION name="Compute the floor" />
      <SYNTAX name="Result = var.Floor(  )" type="func" />
      <KEYWORD name="L64" link="IDL_Number.htm#lass=" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Imaginary" link="kanchor5928">
      <DESCRIPTION name="Return the imaginary value" />
      <SYNTAX name="Result = var.Imaginary(  )" type="func" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Mean" link="kanchor5929">
      <DESCRIPTION name="Compute the mean" />
      <SYNTAX name="Result = var.Mean( [DIMENSION=value] [, /DOUBLE] [, /NAN] )" type="func" />
      <KEYWORD name="DIMENSION" link="IDL_Number.htm#lass=" />
      <KEYWORD name="DOUBLE" link="IDL_Number.htm#lass=" />
      <KEYWORD name="NAN" link="IDL_Number.htm#lass=" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Median" link="kanchor5930">
      <DESCRIPTION name="Compute the median" />
      <SYNTAX name="Result = var.Median( [Width] [, DIMENSION=value] [, /DOUBLE] [, /EVEN]  )" type="func" />
      <ARGUMENT name="Width" link="IDL_Number.htm" />
      <KEYWORD name="DIMENSION" link="IDL_Number.htm#lass=" />
      <KEYWORD name="DOUBLE" link="IDL_Number.htm#lass=" />
      <KEYWORD name="EVEN" link="IDL_Number.htm#lass=" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Max" link="kanchor5931">
      <DESCRIPTION name="Return the value of the largest element" />
      <SYNTAX name="Result = var.Max( [Max_Subscript] [, /ABSOLUTE] [, DIMENSION=value] [, MIN=variable] [, /NAN] [, SUBSCRIPT_MIN=variable] )" type="func" />
      <ARGUMENT name="Max_Subscript" link="IDL_Number.htm" />
      <KEYWORD name="ABSOLUTE" link="IDL_Number.htm#lass=" />
      <KEYWORD name="DIMENSION" link="IDL_Number.htm#lass=" />
      <KEYWORD name="MIN" link="IDL_Number.htm#lass=" />
      <KEYWORD name="NAN" link="IDL_Number.htm#lass=" />
      <KEYWORD name="SUBSCRIPT_MIN" link="IDL_Number.htm#lass=" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Min" link="kanchor5932">
      <DESCRIPTION name="Return the value of the smallest element" />
      <SYNTAX name="Result = var.Min( [Min_Subscript] [, /ABSOLUTE] [, DIMENSION=value] [, MAX=variable] [, /NAN] [, SUBSCRIPT_MAX=variable] )" type="func" />
      <ARGUMENT name="Min_Subscript" link="IDL_Number.htm" />
      <KEYWORD name="ABSOLUTE" link="IDL_Number.htm#lass=" />
      <KEYWORD name="DIMENSION" link="IDL_Number.htm#lass=" />
      <KEYWORD name="MAX" link="IDL_Number.htm#lass=" />
      <KEYWORD name="NAN" link="IDL_Number.htm#lass=" />
      <KEYWORD name="SUBSCRIPT_MAX" link="IDL_Number.htm#lass=" />
    </METHOD>
    <METHOD class="IDL_Number" name="IDL_Number::Product" link="kanchor5933">
      <DESCRIPTION name="Compute the product" />
      <SYNTAX name="Result = var.Product(  )" type="func" />
      <KEYWORD name="CUMULATIVE" link="IDL_Number.htm#lass=" />
      <KEYWORD name="INTEGER" link="IDL_Number.htm#lass=" />
      <KEYWORD name="NAN" link="IDL_Number.htm#lass=" />