=== EarthObservation/RVT/RVT_2.3_Win64/IDL85/help/itools.xsd
<?xml version="1.0"?>

<!--
$Id: //depot/Release/ENVI53_IDL85/idl/idldir/help/itools.xsd#1 $
   Copyright (c) 2003-2015, Exelis Visual Information Solutions, Inc. All
   rights reserved. Unauthorized reproduction is prohibited.
-->

<!--
    xmlns is the default XMLSchema namespace.
    targetNamespace is the namespace whose elements we are defining.
    elementFormDefault="qualified" directs that any documents conforming
        to this schema must be namespace qualified.
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.ittvis.com"
    elementFormDefault="qualified">

  <element name="Help">
    <complexType>
      <sequence>

        <element name="Topic" minOccurs="0" maxOccurs="unbounded">
          <complexType>
            <sequence>

              <element name="Keyword" type="string" minOccurs="1" maxOccurs="unbounded" />

              <element name="Link" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                  <simpleContent>
                    <extension base="string">
                      <attribute name="type" type="string" use="required" />
                      <attribute name="book" type="string" />
                    </extension>
                  </simpleContent>
                </complexType>
              </element>

            </sequence>
          </complexType>
        </element>

      </sequence>
    </complexType>
  </element>

</schema>

=== EarthObservation/RVT/RVT_2.3_Win64/IDL85/help/idlithelp.xml
<?xml version="1.0" standalone="no"?>
<!--
$Id: //depot/Release/ENVI53_IDL85/idl/idldir/help/idlithelp.xml#1 $
   Copyright (c) 2003-2015, Exelis Visual Information Solutions, Inc. All
   rights reserved. Unauthorized reproduction is prohibited.
-->

<!--
   xmlns is the namespace for this XML file.
   xmlns:xsi is the XMLSchema namespace containing the
       xsi:schemaLocation attribute.
   xsi:schemaLocation states that the namespace is defined by
       the given schema document.
-->
<Help xmlns="http://www.exelisvis.com"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.exelisvis.com itools.xsd">

<!-- Sample topic:

Note: all tags are case sensitive.

<Topic>
   <Keyword>Keyword1</Keyword>   (All Keywords must appear before Links)
   <Keyword>Keyword2</Keyword>
   ...
   <Link type="TYPEA">LinkA</Link>  (type is a required attribute)
   <Link type="TYPEB">LinkB</Link>
   ...
</Topic>

Example:

<Topic>
   <Keyword>IDLitVisSurface</Keyword>
   <Link type="IDLHELP">IDE_MOTIF</Link>
   <Link type="MSHTMLHELP">12345</Link>
   <Link type="PDF" book="mybook.pdf">VisSurface</Link>
   <Link type="HTML">VisSurface.html</Link>
   <Link type="TEXT">VisSurface.txt</Link>
</Topic>

-->


<!--    All keywords which have their own topic go here.    -->

<Topic>
   <Keyword>IT_ABOUT</Keyword>
   <Keyword>idlitophelpitools</Keyword>
   <Link type="IDLHELP">Introducing_the_IDL_iTools</Link>
</Topic>

<Topic>
   <Keyword>iToolsExportWizard</Keyword>
   <Link type="IDLHELP">IT_DATA_EXPORT</Link>
</Topic>

<Topic>
   <Keyword>iToolsImportWizard</Keyword>
   <Link type="IDLHELP">IT_DATA_WIZ</Link>
</Topic>

<Topic>
   <Keyword>iToolsUnknownData</Keyword>
   <Keyword>iToolsGridWizard</Keyword>
   <Link type="IDLHELP">IT_DATA_UNKNOWN</Link>
</Topic>


<!--    List of all IDLit* classes -->

<Topic>
   <Keyword>idlitgeneralsettings</Keyword>
   <Link type="IDLHELP">ITOOL_PREFS_BROWSER</Link>
</Topic>

<Topic>
   <Keyword>idlitophelpdatamanager</Keyword>
   <Keyword>idlitopbrowserdata</Keyword>
   <Link type="IDLHELP">IT_DATAMANAGER</Link>
</Topic>

<Topic>
   <Keyword>idlitopinsertvis</Keyword>
   <Link type="IDLHELP">IT_INSERT_VIZ</Link>
</Topic>

<Topic>
   <Keyword>idlitopbrowseroperation</Keyword>
   <Link type="IDLHELP">ITOOL_OPS_BROWSER</Link>
</Topic>


<Topic>
   <Keyword>idlitopeditparameters</Keyword>
   <Keyword>idlitophelpparameditor</Keyword>
   <Link type="IDLHELP">IT_PARAM_EDIT</Link>
</Topic>

<Topic>
   <Keyword>idlitopfilterroberts</Keyword>
   <Keyword>idlitopfiltersobel</Keyword>
   <Keyword>idlitopmedianfilter</Keyword>
   <Keyword>idlitopsmooth</Keyword>
   <Keyword>idlitopconvolution</Keyword>
   <Keyword>idlitopcurvefitting</Keyword>
   <Keyword>idlitopunsharpmask</Keyword>
   <Link type="IDLHELP">IT_OPS_FILTERS</Link>
</Topic>

<Topic>
   <Keyword>idlitophistogram</Keyword>
   <Link type="IDLHELP">IT_OPS_HISTOGRAM</Link>
</Topic>

<Topic>
   <Keyword>idlitopinsertcontour</Keyword>
   <Link type="IDLHELP">IT_OPS_CONTOUR</Link>
</Topic>

<Topic>
   <Keyword>idlitopimageplaneiimage</Keyword>
   <Link type="IDLHELP">IT_OPS_IMAGEPLANE</Link>
</Topic>

<Topic>
   <Keyword>idlitopinsertimage</Keyword>
   <Link type="IDLHELP">IT_OPS_IMAGE</Link>
</Topic>

<Topic>
   <Keyword>idlitopvectorstreamline</Keyword>
   <Keyword>idlitopvectorcontour</Keyword>
   <Link type="IDLHELP">IT_OPS_VECTOR</Link>
</Topic>

<Topic>
   <Keyword>idlitopinsertimageplane</Keyword>
   <Keyword>idlitopisosurface</Keyword>
   <Keyword>idlitopintvol</Keyword>
   <Link type="IDLHELP">IT_OPS_VOLUME</Link>
</Topic>

<Topic>
   <Keyword>idlitopinsertsurface</Keyword>
   <Link type="IDLHELP">IT_OPS_SURFACE</Link>
</Topic>

<Topic>
   <Keyword>idlitopmorph</Keyword>
   <Keyword>idlitopmorphclose</Keyword>
   <Keyword>idlitopmorphdilate</Keyword>
   <Keyword>idlitopmorpherode</Keyword>
   <Keyword>idlitopmorphgradient</Keyword>
   <Keyword>idlitopmorphopen</Keyword>
   <Keyword>idlitopmorphtophat</Keyword>
   <Link type="IDLHELP">IT_OPS_MORPH</Link>
</Topic>

<Topic>
   <Keyword>idlitopregiongrow</Keyword>
   <Link type="IDLHELP">IT_OPS_REGIONGROW</Link>
</Topic>

<Topic>
   <Keyword>idlitopresample</Keyword>
   <Keyword>idlitoprotatedata</Keyword>
   <Keyword>idlitopinvert</Keyword>
   <Keyword>idlitopbytscl</Keyword>
   <Keyword>idlitopscalefactor</Keyword>
   <Link type="IDLHELP">IT_OPS_TRANSFORM</Link>
</Topic>

<Topic>
   <Keyword>idlitoprotateangle</Keyword>
   <Keyword>idlitoprotatebyangle</Keyword>
   <Keyword>idlitoprotateleft</Keyword>
   <Keyword>idlitoprotateright</Keyword>
   <Keyword>idlitopfliphorizontal</Keyword>
   <Keyword>idlitopflipvertical</Keyword>
   <Link type="IDLHELP">IT_OPS_ROTATE</Link>
</Topic>

<Topic>
   <Keyword>idlitopstatistics</Keyword>
   <Link type="IDLHELP">IT_OPS_STATS</Link>
</Topic>

<Topic>
   <Keyword>idlitreadascii</Keyword>
   <Keyword>idlitreadbinary</Keyword>
   <Keyword>idlitreadbmp</Keyword>
   <Keyword>idlitreaddicom</Keyword>
   <Keyword>idlitreader</Keyword>
   <Keyword>idlitreadisv</Keyword>
   <Keyword>idlitreadjpeg</Keyword>
   <Keyword>idlitreadpict</Keyword>
   <Keyword>idlitreadpng</Keyword>
   <Keyword>idlitreadtiff</Keyword>
   <Keyword>idlitreadwav</Keyword>
   <Keyword>idlitreadjpeg2000</Keyword>
   <Keyword>idlitreadshapefile</Keyword>
   <Link type="IDLHELP">ITOOL_PREFS_FILEREAD</Link>
</Topic>

<Topic>
   <Keyword>idlitopmacrorecordstart</Keyword>
   <Keyword>idlitopmacrorecordstop</Keyword>
   <Link type="IDLHELP">ITOOL_MACRO_REC</Link>
</Topic>

<Topic>
   <Keyword>idlitoprunmacro</Keyword>
   <Keyword>iToolsRunMacro</Keyword>
   <Link type="IDLHELP">ITOOL_MACRO_RUN</Link>
</Topic>

<Topic>
   <Keyword>iToolsMacroEditor</Keyword>
   <Keyword>idlitopmacroeditor</Keyword>
   <Link type="IDLHELP">ITOOL_MACRO_EDIT</Link>
</Topic>

<Topic>
   <Keyword>idlitopstylecreate</Keyword>
   <Keyword>iToolsCreateStyle</Keyword>
   <Link type="IDLHELP">ITOOL_STYLE_CREATE</Link>
</Topic>

<Topic>
   <Keyword>idlitopstyleapply</Keyword>
   <Keyword>iToolsApplyStyle</Keyword>
   <Link type="IDLHELP">ITOOL_STYLE_APPLY</Link>
</Topic>

<Topic>
   <Keyword>iToolsStyleEditor</Keyword>
   <Keyword>idlitopstyleeditor</Keyword>
   <Link type="IDLHELP">ITOOL_STYLE_EDIT</Link>
</Topic>

<Topic>
   <Keyword>idlittoolcontour</Keyword>
   <Link type="IDLHELP">Working_with_Contours</Link>
</Topic>

<Topic>
   <Keyword>idlittoolimage</Keyword>
   <Link type="IDLHELP">Working_with_Images</Link>
</Topic>

<Topic>
   <Keyword>idlitopcropimage</Keyword>
   <Keyword>idlitopcropimagegrid</Keyword>
   <Link type="IDLHELP">IIMAGE_OPS</Link>
</Topic>

<Topic>
   <Keyword>idlittoolplot</Keyword>
   <Link type="IDLHELP">Working_with_Plots</Link>
</Topic>

<Topic>
   <Keyword>idlittoolsurface</Keyword>
   <Link type="IDLHELP">Working_with_Surfaces</Link>
</Topic>

<Topic>
   <Keyword>idlittoolvolume</Keyword>
   <Link type="IDLHELP">Working_with_Volumes</Link>
</Topic>

<Topic>
   <Keyword>idlittoolmap</Keyword>
   <Link type="IDLHELP">Working_with_Maps</Link>
</Topic>

<Topic>
   <Keyword>idlittoolvector</Keyword>
   <Link type="IDLHELP">Working_with_Vectors</Link>
</Topic>

<Topic>
   <Keyword>idlitvismapprojection</Keyword>
   <Keyword>idlitopmapprojection</Keyword>
   <Link type="IDLHELP">IT_MAP_PROJ</Link>
</Topic>

<Topic>
   <Keyword>iToolsMapRegisterImage</Keyword>
   <Keyword>idlitopmapregisterimage</Keyword>
   <Link type="IDLHELP">IT_MAP_REG_IMAGE</Link>
</Topic>

<Topic>
   <Keyword>idlitvismapgrid</Keyword>
   <Keyword>idlitvismapgridline</Keyword>
   <Link type="IDLHELP">IT_VISMAP_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisshapepolygon</Keyword>
   <Link type="IDLHELP">IT_VISSHPOLYGON_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisshapepolyline</Keyword>
   <Link type="IDLHELP">IT_VISSHPOLYLINE_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisshapepoint</Keyword>
   <Link type="IDLHELP">IT_VISSHPOINT_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisstreamline</Keyword>
   <Link type="IDLHELP">IT_VISSTREAMLINE_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisaxis</Keyword>
   <Keyword>idlitvisaxisdual</Keyword>
   <Keyword>idlitvisdataaxes</Keyword>
   <Link type="IDLHELP">IT_VISAXES_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitviscolorbar</Keyword>
   <Link type="IDLHELP">IT_VISCOLORBAR_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitviscontour</Keyword>
   <Keyword>idlitviscontourlevel</Keyword>
   <Link type="IDLHELP">IT_VISCONTOUR_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisdataspace</Keyword>
   <Keyword>idlitvisnormdataspace</Keyword>
   <Link type="IDLHELP">IT_DATASPACE_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvishistogram</Keyword>
   <Link type="IDLHELP">IT_VISHISTOGRAM_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisimage</Keyword>
   <Link type="IDLHELP">IT_VISIMAGE_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisimageplane</Keyword>
   <Link type="IDLHELP">IT_VISIMAGEPLANE_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisintvol</Keyword>
   <Link type="IDLHELP">IT_VISINTERVALVOL_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisisosurface</Keyword>
   <Link type="IDLHELP">IT_VISISOSURFACE_PROPS</Link>
</Topic>

<!--
The following items all subclass idlitvislegenditem
-->
<Topic>
   <Keyword>idlitvislegend</Keyword>
   <Link type="IDLHELP">IT_LEGEND_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvislegendcontouritem</Keyword>
   <Link type="IDLHELP">IT_LEGEND_CONTOUR</Link>
</Topic>

<Topic>
   <Keyword>idlitvislegendcontourlevelitem</Keyword>
   <Link type="IDLHELP">IT_LEGEND_CONTOUR_LEVEL</Link>
</Topic>

<Topic>
   <Keyword>idlitvislegendplotitem</Keyword>
   <Link type="IDLHELP">IT_LEGEND_PLOT</Link>
</Topic>

<Topic>
   <Keyword>idlitvislegendsurfaceitem</Keyword>
   <Link type="IDLHELP">IT_LEGEND_SURFACE</Link>
</Topic>

<Topic>
   <Keyword>idlitvislight</Keyword>
   <Link type="IDLHELP">IT_VISLIGHT_PROPS</Link>
</Topic>

<Topic>
   <Keyword>idlitvisplot</Keyword>
